# Override any default configurations for the expected environment and RL training algorithm here
#e.g.
#  env:
#   action_scale: 1.0
#
#  Will rewrite the default experiment name to "test" from the provided config passed to run.py 
# 
# See doc/templates

reward_config:
    scales: 
      # Tracking related rewards.
      tracking_lin_vel: 0.0
      tracking_ang_vel: 0.0
      # Base related rewards.
      lin_vel_z: 0.0
      ang_vel_xy: 0.0
      orientation: 0.0
      base_height: 0.0
      # Energy related rewards.
      torques: 0.0
      action_rate: 0.0
      energy: 0.0
      # Feet related rewards.
      feet_clearance: 0.0
      feet_air_time: 0.0
      feet_slip: 0.0
      feet_height: 0.0
      feet_phase: 0.0
      # Other rewards.
      stand_still: 0.0
      alive: 0.0
      termination: 0.0
      # Pose related rewards.
      joint_deviation_knee: 0.0
      joint_deviation_hip: 0.0
      dof_pos_limits: 0.0
      pose: 0.0

brax_ppo_agent:
  num_timesteps: 150_000_000
  num_evals: 15
  clipping_epsilon: 0.2
  reward_scaling: 1.0
  episode_length: 1000
  normalize_observations: True
  action_repeat: 1
  unroll_length: 20
  num_minibatches: 32
  num_updates_per_batch: 4
  discounting: 0.97
  learning_rate: 0.0003
  entropy_cost: 0.005
  num_envs: 8192
  batch_size: 256
  max_grad_norm: 1.0
  network_factory:
    policy_hidden_layer_sizes: [512, 256, 128]
    value_hidden_layer_sizes: [512, 256, 128]
    policy_obs_key: "state"
    value_obs_key: "privileged_state"
  num_resets_per_eval : 1