#!/usr/bin/env bash
set -euo pipefail

MOTION_DIR="${MOTION_DIR:-/cephfs/holosoma/data/lafan/retargeted/ch_robot_stance_flatfoot_locomotion_full_floor_norm_with_vel}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-lafan_walk_tracking}"
MOTION_MANIFEST="${MOTION_MANIFEST:-manifests/${EXPERIMENT_NAME}_manifest.txt}"
NUM_ENVS="${NUM_ENVS:-8192}"
NUM_GPUS="${NUM_GPUS:-1}"
LOG_ROOT="${LOG_ROOT:-logs/rl_games/humanoid_flat_direct/${EXPERIMENT_NAME}}"
CHECKPOINT="${CHECKPOINT:-}"
RESUME_LAST="${RESUME_LAST:-0}"
FAST_TRAIN="${FAST_TRAIN:-1}"
PYTHON_CMD=()
if [[ -n "${ISAAC_PYTHON:-}" ]]; then
  PYTHON_CMD=("${ISAAC_PYTHON}")
elif [[ -n "${ISAACSIM_ROOT_PATH:-}" && -x "${ISAACSIM_ROOT_PATH}/python.sh" ]]; then
  PYTHON_CMD=(env -u CONDA_PREFIX -u CONDA_DEFAULT_ENV -u CONDA_PROMPT_MODIFIER -u CONDA_SHLVL "${ISAACSIM_ROOT_PATH}/python.sh")
elif [[ -x "/isaac-sim/python.sh" ]]; then
  PYTHON_CMD=(env -u CONDA_PREFIX -u CONDA_DEFAULT_ENV -u CONDA_PROMPT_MODIFIER -u CONDA_SHLVL "/isaac-sim/python.sh")
elif [[ -n "${ISAACLAB_PATH:-}" && -x "${ISAACLAB_PATH}/isaaclab.sh" && -z "${CONDA_PREFIX:-}" && -z "${VIRTUAL_ENV:-}" ]]; then
  PYTHON_CMD=("${ISAACLAB_PATH}/isaaclab.sh" "-p")
else
  PYTHON_CMD=("${PYTHON:-python}")
fi

WALK_CLIPS=(
  walk1_subject1_original_floor_norm_with_vel.npz
  walk1_subject2_original_floor_norm_with_vel.npz
  walk1_subject5_original_floor_norm_with_vel.npz
  walk2_subject1_original_floor_norm_with_vel.npz
  walk2_subject3_original_floor_norm_with_vel.npz
  walk2_subject4_original_floor_norm_with_vel.npz
  walk3_subject1_original_floor_norm_with_vel.npz
  walk3_subject2_original_floor_norm_with_vel.npz
  walk3_subject3_original_floor_norm_with_vel.npz
  walk3_subject4_original_floor_norm_with_vel.npz
  walk3_subject5_original_floor_norm_with_vel.npz
  walk4_subject1_original_floor_norm_with_vel.npz
)

if [[ ! -d "${MOTION_DIR}" ]]; then
  echo "[ERROR] Motion directory does not exist: ${MOTION_DIR}" >&2
  exit 1
fi

if [[ ! "${NUM_GPUS}" =~ ^[0-9]+$ ]] || (( NUM_GPUS < 1 )); then
  echo "[ERROR] NUM_GPUS must be a positive integer, got: ${NUM_GPUS}" >&2
  exit 1
fi

mkdir -p "$(dirname "${MOTION_MANIFEST}")"
missing=0
{
  printf '# Auto-generated by %s\n' "$0"
  printf '# Walk-only LAFAN manifest for %s\n' "${MOTION_DIR}"
} > "${MOTION_MANIFEST}"
for clip in "${WALK_CLIPS[@]}"; do
  path="${MOTION_DIR}/${clip}"
  if [[ ! -f "${path}" ]]; then
    echo "[ERROR] Missing walk clip: ${path}" >&2
    missing=1
  else
    printf '%s\n' "${path}" >> "${MOTION_MANIFEST}"
  fi
done

if [[ "${missing}" != "0" ]]; then
  exit 1
fi

echo "[INFO] Training LAFAN walk tracking with ${#WALK_CLIPS[@]} clips"
echo "[INFO] Experiment: ${EXPERIMENT_NAME}"
echo "[INFO] Motion dir: ${MOTION_DIR}"
echo "[INFO] Manifest: ${MOTION_MANIFEST}"
echo "[INFO] Num envs per process: ${NUM_ENVS}"
echo "[INFO] Python: ${PYTHON_CMD[*]}"
if (( NUM_GPUS > 1 )); then
  echo "[INFO] Distributed GPUs: ${NUM_GPUS} (total envs ~= $((NUM_ENVS * NUM_GPUS)))"
fi

if [[ "${CHECKPOINT}" == "latest" ]]; then
  RESUME_LAST=1
  CHECKPOINT=""
fi

if [[ -n "${CHECKPOINT}" && "${RESUME_LAST}" != "0" ]]; then
  echo "[ERROR] Set either CHECKPOINT or RESUME_LAST=1, not both." >&2
  exit 1
fi

if [[ "${RESUME_LAST}" != "0" ]]; then
  if [[ ! -d "${LOG_ROOT}" ]]; then
    echo "[ERROR] Cannot resume: log root does not exist: ${LOG_ROOT}" >&2
    exit 1
  fi
  CHECKPOINT="$(
    find "${LOG_ROOT}" -path '*/nn/*.pth' -type f -printf '%T@ %p\n' 2>/dev/null \
      | sort -nr \
      | awk 'NR==1 {sub(/^[^ ]+ /, ""); print}'
  )"
  if [[ -z "${CHECKPOINT}" ]]; then
    echo "[ERROR] Cannot resume: no checkpoints found under ${LOG_ROOT}" >&2
    exit 1
  fi
fi

TRAIN_ARGS=(
  --task=Isaac-Humanoid-Locomotion-Flat-Direct-v0
  --num_envs="${NUM_ENVS}"
  --headless
)

if (( NUM_GPUS > 1 )); then
  TRAIN_ARGS+=(--distributed)
fi

if [[ -n "${MAX_ITERATIONS:-}" ]]; then
  TRAIN_ARGS+=(--max_iterations "${MAX_ITERATIONS}")
fi

if [[ -n "${SEED:-}" ]]; then
  TRAIN_ARGS+=(--seed "${SEED}")
fi

if [[ -n "${SIGMA:-}" ]]; then
  TRAIN_ARGS+=(--sigma "${SIGMA}")
fi

if [[ -n "${CHECKPOINT}" ]]; then
  echo "[INFO] Resuming from checkpoint: ${CHECKPOINT}"
  TRAIN_ARGS+=(--checkpoint "${CHECKPOINT}")
fi

COMMON_OVERRIDES=(
  env.motion_reference_dir="${MOTION_DIR}"
  env.motion_manifest_file="${MOTION_MANIFEST}"
  env.motion_reference_playback=false
  env.motion_random_start=true
  env.motion_min_length_s=1.0
  env.motion_cache_on_gpu=true
  +agent.params.config.full_experiment_name="${EXPERIMENT_NAME}"
)

if [[ "${FAST_TRAIN}" != "0" ]]; then
  COMMON_OVERRIDES+=(
    env.events=null
    env.enable_adr=false
    env.enable_contact_rewards=false
    env.enable_contact_sensors=false
    env.enable_reward_logging=false
    env.push_force_range=[0.0,0.0]
    env.reset_joint_pos_noise=0.0
    env.reset_joint_vel_noise=0.0
    env.robot.spawn.activate_contact_sensors=false
    env.robot.spawn.articulation_props.enabled_self_collisions=false
    env.robot.spawn.articulation_props.solver_position_iteration_count=4
    env.robot.spawn.articulation_props.solver_velocity_iteration_count=0
  )
fi

if (( NUM_GPUS > 1 )); then
  CMD=(
    "${PYTHON_CMD[@]}" -m torch.distributed.run
    --standalone
    --nnodes=1
    --nproc_per_node="${NUM_GPUS}"
    scripts/rl_games/train.py
    "${TRAIN_ARGS[@]}"
    "${COMMON_OVERRIDES[@]}"
    "$@"
  )
else
  CMD=(
    "${PYTHON_CMD[@]}" scripts/rl_games/train.py
    "${TRAIN_ARGS[@]}"
    "${COMMON_OVERRIDES[@]}"
    "$@"
  )
fi

if [[ "${DRY_RUN:-0}" != "0" ]]; then
  printf '[DRY_RUN]'
  printf ' %q' "${CMD[@]}"
  printf '\n'
  exit 0
fi

"${CMD[@]}"
