"""Create a review-friendly zip archive of this simulator repository.

The script packages the project source and small root files while skipping
generated folders and local-only state. It exists so teammates can produce the
same upload artifact with one command and without needing git to be installed.
"""

from __future__ import annotations

import argparse
import os
import zipfile
from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT = Path("exports") / "simulation_robocup_export.zip"

EXCLUDED_DIR_NAMES = {
    ".git",
    ".idea",
    ".vscode",
    ".cache",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    ".ipynb_checkpoints",
    "env",
    "exports",
    "logs",
    "mujoco_menagerie",
    "outputs",
    "results",
    "runs",
    "venv",
    "wandb",
}

EXCLUDED_FILE_SUFFIXES = {
    ".avi",
    ".cache",
    ".log",
    ".mkv",
    ".mov",
    ".mp4",
    ".pyo",
    ".pyc",
    ".tmp",
    ".webm",
    ".zip",
}


@dataclass(frozen=True)
class ExportResult:
    """Summary of a completed repository export.

    The export workflow passes this object to the final reporting function so
    output stays consistent for terminal, PyCharm, and VS Code runs.
    """

    output_path: Path
    file_count: int


def repo_root() -> Path:
    """Return the repository root based on this script's location.

    Returns:
        Absolute path to the project root.

    Failure cases:
        This assumes the script remains under `scripts/`.
    """

    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    """Parse export command-line options.

    Returns:
        Parsed arguments with a predictable default output path.
    """

    parser = argparse.ArgumentParser(
        description="Export this repository to a review-friendly zip archive."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Zip file path to write, relative to the repo root unless absolute.",
    )
    parser.add_argument(
        "--pause",
        action="store_true",
        help="Wait for Enter before exiting. Useful when a Run window closes quickly.",
    )
    return parser.parse_args()


def log(message: str = "") -> None:
    """Print a status message immediately.

    Args:
        message: Text to write to stdout.

    Side effects:
        Flushes stdout so IDE run windows show progress before the script exits.
    """

    print(message, flush=True)


def output_path_from_arg(root: Path, output_arg: str) -> Path:
    """Resolve the requested zip output path.

    Args:
        root: Repository root.
        output_arg: User-provided output path.

    Returns:
        Absolute path where the zip should be written.
    """

    output_path = Path(output_arg).expanduser()
    if not output_path.is_absolute():
        output_path = root / output_path
    return output_path.resolve()


def has_excluded_parent(relative_path: Path) -> bool:
    """Check whether a path lives under a folder that should be skipped.

    Args:
        relative_path: Path relative to the repository root.

    Returns:
        True when any path component is an excluded directory name.
    """

    return any(part in EXCLUDED_DIR_NAMES for part in relative_path.parts)


def should_include_file(path: Path, root: Path, output_path: Path) -> bool:
    """Decide whether a file belongs in the export archive.

    Args:
        path: Candidate file path.
        root: Repository root.
        output_path: Absolute zip path being written.

    Returns:
        True when the file should be included in the export.
    """

    relative_path = path.relative_to(root)

    # Avoid recursively including the zip being written or older export zips.
    if path.resolve() == output_path or has_excluded_parent(relative_path):
        return False

    # Skip generated bytecode, logs, temporary files, and rendered videos.
    if path.suffix.lower() in EXCLUDED_FILE_SUFFIXES:
        return False

    return True


def iter_export_files(root: Path, output_path: Path) -> list[Path]:
    """Collect files that should be written to the export zip.

    Args:
        root: Repository root.
        output_path: Absolute zip path being written.

    Returns:
        Sorted list of files to include.
    """

    included_files: list[Path] = []
    for current_dir, dirnames, filenames in os.walk(root, topdown=True):
        # Prune generated trees before walking them.  In particular, scanning
        # the multi-gigabyte WSL venv is both slow and vulnerable to Windows
        # stat errors on its platform-specific links.
        dirnames[:] = sorted(
            name for name in dirnames if name not in EXCLUDED_DIR_NAMES
        )
        directory = Path(current_dir)
        for filename in sorted(filenames):
            path = directory / filename
            relative_path = path.relative_to(root)
            if has_excluded_parent(relative_path):
                continue
            try:
                is_file = path.is_file()
            except OSError:
                continue
            if is_file and should_include_file(path, root, output_path):
                included_files.append(path)
    return sorted(included_files)


def write_zip(root: Path, output_path: Path, files: list[Path]) -> None:
    """Write the selected project files to a zip archive.

    Args:
        root: Repository root.
        output_path: Absolute zip path being written.
        files: Files selected for inclusion.

    Side effects:
        Creates the output directory and writes the zip file.
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Store paths relative to the repo root so the archive extracts cleanly.
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in files:
            archive.write(file_path, file_path.relative_to(root).as_posix())


def print_summary(result: ExportResult) -> None:
    """Print the export result in a human-readable format.

    Args:
        result: Export path and file count from the completed run.
    """

    excluded_folders = ", ".join(sorted(EXCLUDED_DIR_NAMES))
    log()
    log("Export complete.")
    log(f"Zip written to: {result.output_path}")
    log(f"Files included: {result.file_count}")
    log(f"Major folders excluded: {excluded_folders}")


def maybe_pause(should_pause: bool) -> None:
    """Optionally wait before process exit.

    Args:
        should_pause: Whether to wait for user input.

    Side effects:
        Reads from stdin when `--pause` was requested.
    """

    if should_pause:
        input("Press Enter to close this export window...")


def main() -> None:
    """Create the repository export zip using the configured exclusions.

    Side effects:
        Writes `exports/simulation_robocup_export.zip` by default and prints
        progress messages that are visible in IDE run consoles.
    """

    args = parse_args()
    root = repo_root()
    output_path = output_path_from_arg(root, args.output)

    log("Starting RoboCup repository export...")
    log(f"Repository root: {root}")
    log(f"Output zip: {output_path}")
    log("Collecting files...")

    files = iter_export_files(root, output_path)

    log(f"Writing {len(files)} files...")
    write_zip(root, output_path, files)
    print_summary(ExportResult(output_path=output_path, file_count=len(files)))
    maybe_pause(args.pause)


if __name__ == "__main__":
    main()
