train:
  environment: "DefaultHumanoidJoyStickFlatTerrain" #"DefaultHumanoidJoystickRoughTerrain"
  framework: "brax_ppo"
  settings:
    enable_checkpoints: true
    enable_record: true
    enable_logging: true
    enable_testing: true

simulate:
  environment: "DefaultHumanoidJoyStickFlatTerrain"
  settings:
    enable_checkpoints: true
    enable_rendering: true
    enable_record: true
    enable_logging: false

general:
  settings:
    enable_logging: false
